namespace IllusionCards.AI.Chara.Friendly;

public static partial class AiFriendlyNameLookup
{
	public static string GetFriendlyNameByCategoryID(in int categoryID, in int itemID) => categoryID switch
	{
		//0 => throw new NotImplementedException(), //cha_sample_m
		//1 => throw new NotImplementedException(), //cha_sample_f
		//3 => throw new NotImplementedException(), //init_mind_param
		//5 => throw new NotImplementedException(), //cha_sample_voice
		6 => GetFriendlyMoleLayoutName(itemID), //mole_layout
		7 => GetFriendlyFacePaintLayoutName(itemID), //facepaint_layout
		8 => GetFriendlyBodyPaintLayoutName(itemID), //bodypaint_layout
		110 => GetFriendlyMaleFaceContourName(itemID), //mo_head
		111 => GetFriendlyMaleFaceSkinName(itemID), //mt_skin_f
		112 => GetFriendlyMaleFaceWrinklesName(itemID), //mt_detail_f
		121 => GetFriendlyMaleBeardName(itemID), //mt_beard
		131 => GetFriendlyMaleSkinName(itemID), //mt_skin_b
		132 => GetFriendlyMaleSkinBuildName(itemID), //mt_detail_b
		133 => GetFriendlyMaleSuntanName(itemID), //mt_sunburn
		140 => GetFriendlyMaleTopName(itemID), //mo_top
		141 => GetFriendlyMaleBottomName(itemID), //mo_bot
		144 => GetFriendlyMaleGlovesName(itemID), //mo_gloves
		147 => GetFriendlyMaleShoesName(itemID), //mo_shoes
		210 => GetFriendlyFemaleFaceContourName(itemID), //fo_head
		211 => GetFriendlyFemaleFaceSkinName(itemID), //ft_skin_f
		212 => GetFriendlyFemaleFaceWrinklesName(itemID), //ft_detail_f
		240 => GetFriendlyFemaleTopName(itemID), //fo_top
		241 => GetFriendlyFemaleBottomName(itemID), //fo_bot
		242 => GetFriendlyFemaleInnerTopName(itemID), //fo_inner_t
		243 => GetFriendlyFemaleInnerBottomName(itemID), //fo_inner_b
		244 => GetFriendlyFemaleGlovesName(itemID), //fo_gloves
		245 => GetFriendlyFemalePantyhoseName(itemID), //fo_panst
		246 => GetFriendlyFemaleSocksName(itemID), //fo_socks
		247 => GetFriendlyFemaleShoesName(itemID), //fo_shoes
		300 => GetFriendlyHairBackName(itemID), //so_hair_b
		301 => GetFriendlyHairFrontName(itemID), //so_hair_f
		302 => GetFriendlyHairSideName(itemID), //so_hair_s
		303 => GetFriendlyHairExtensionName(itemID), //so_hair_o
		305 => GetFriendlyHairColorPresetName(itemID), //preset_hair_color
		306 => GetFriendlyHairMeshPatternName(itemID), //st_hairmeshptn
		336 => GetFriendlySkinColorPresetName(itemID), //preset_skin_color
		348 => GetFriendly_st_pattern_Name(itemID), //st_pattern
		350 => "None", //ao_none
		351 => GetFriendlyHeadAccessoryName(itemID), //ao_head
		352 => GetFriendlyEarringName(itemID), //ao_ear
		353 => GetFriendlyGlassesName(itemID), //ao_glasses
		354 => GetFriendlyFaceAccessoryName(itemID), //ao_face
		355 => GetFriendlyNeckAccessoryName(itemID), //ao_neck
		356 => GetFriendlyShoulderAccessoryName(itemID), //ao_shoulder
		357 => GetFriendlyChestAccessoryName(itemID), //ao_chest
		358 => GetFriendlyWaistAccessoryName(itemID), //ao_waist
		359 => GetFriendlyBackAccessoryName(itemID), //ao_back
		360 => GetFriendlyArmAccessoryName(itemID), //ao_arm
		361 => GetFriendlyHandAccessoryName(itemID), //ao_hand
		362 => GetFriendlyLegAccessoryName(itemID), //ao_leg
		363 => GetFriendlyCrotchAccessoryName(itemID), //ao_kokan
													   //500 => GetFriendlyMaleCustomPoseName(itemID), //custom_pose_m
													   //501 => GetFriendlyFemaleCustomPoseName(itemID), //custom_pose_f
													   //502 => GetFriendlyMaleCustomEyebrowName(itemID), //custom_eyebrow_m
													   //503 => GetFriendlyFemaleCustomEyebrowName(itemID), //custom_eyebrow_f
													   //504 => GetFriendlyMaleCustomEyeName(itemID), //custom_eye_m
													   //505 => GetFriendlyFemaleCustomEyeName(itemID), //custom_eye_f
													   //506 => GetFriendlyMaleCustomMouthName(itemID), //custom_mouth_m
													   //507 => GetFriendlyFemaleCustomMouthName(itemID), //custom_mouth_f
		_ => $"Unknown category ID {categoryID}, item ID {itemID}"
	};

	public static string GetFriendlyClothingPatternByID(in int itemID) => itemID switch
	{
		0 => "None",
		1 => "",
		2 => "",
		3 => "",
		4 => "",
		5 => "",
		6 => "",
		7 => "",
		8 => "",
		9 => "",
		10 => "",
		11 => "",
		12 => "",
		13 => "",
		14 => "",
		15 => "",
		16 => "",
		17 => "",
		18 => "",
		19 => "",
		20 => "",
		21 => "",
		22 => "",
		23 => "",
		24 => "",
		25 => "",
		26 => "",
		27 => "",
		28 => "",
		29 => "",
		30 => "",
		31 => "",
		32 => "",
		33 => "",
		34 => "",
		35 => "",
		36 => "",
		37 => "",
		38 => "",
		39 => "",
		40 => "",
		41 => "",
		42 => "",
		43 => "",
		44 => "",
		45 => "",
		46 => "",
		47 => "",
		48 => "",
		49 => "",
		50 => "",
		51 => "",
		52 => "",
		53 => "",
		54 => "",
		55 => "",
		56 => "",
		_ => "Unknown clothing pattern"
	};
}
