namespace IllusionCards.AI.Chara.Friendly;

public static partial class AiFriendlyNameLookup
{
	public static string GetFriendlyNameByCategoryID(in int categoryID, in int itemID) => categoryID switch
	{
		0 => GetFriendlyMaleSampleCharacterName(itemID), //cha_sample_m
		1 => GetFriendlyFemaleSampleCharacterName(itemID), //cha_sample_f
		3 => GetFriendlyPersonalityName(itemID), //init_mind_param
		4 => GetFriendlyDesireName(itemID), //init_wish_param
		5 => GetFriendlyCharaSampleVoiceName(itemID), //cha_sample_voice
		6 => GetFriendlyMoleLayoutName(itemID), //mole_layout
		7 => GetFriendlyFacepaintLayoutName(itemID), //facepaint_layout
		8 => GetFriendlyBodypaintLayoutName(itemID), //bodypaint_layout
		110 => GetFriendlyMaleFaceContourName(itemID), //mo_head
		111 => GetFriendlyMaleFaceSkinName(itemID), //mt_skin_f
		112 => GetFriendlyMaleFaceWrinklesName(itemID), //mt_detail_f
		121 => GetFriendlyMaleBeardName(itemID), //mt_beard
		131 => GetFriendlyMaleSkinTypeName(itemID), //mt_skin_b
		132 => GetFriendlyMaleSkinBuildName(itemID), //mt_detail_b
		133 => GetFriendlyMaleSuntanName(itemID), //mt_sunburn
		140 => GetFriendlyMaleTopName(itemID), //mo_top
		141 => GetFriendlyMaleBottomName(itemID), //mo_bot
		144 => GetFriendlyMaleGlovesName(itemID), //mo_gloves
		147 => GetFriendlyMaleShoesName(itemID), //mo_shoes
		210 => GetFriendlyFemaleFaceContourName(itemID), //fo_head
		211 => GetFriendlyFemaleFaceSkinName(itemID), //ft_skin_f
		212 => GetFriendlyFemaleFaceWrinklesName(itemID), //ft_detail_f
		231 => GetFriendlyFemaleSkinTypeName(itemID), //ft_skin_b
		232 => GetFriendlyFemaleSkinBuildName(itemID), //ft_detail_b
		233 => GetFriendlyFemaleSuntanName(itemID), //ft_sunburn
		240 => GetFriendlyFemaleTopName(itemID), //fo_top
		241 => GetFriendlyFemaleBottomName(itemID), //fo_bot
		242 => GetFriendlyFemaleInnerTopName(itemID), //fo_inner_t
		243 => GetFriendlyFemaleInnerBottomName(itemID), //fo_inner_b
		244 => GetFriendlyFemaleGlovesName(itemID), //fo_gloves
		245 => GetFriendlyFemalePantyhoseName(itemID), //fo_panst
		246 => GetFriendlyFemaleSocksName(itemID), //fo_socks
		247 => GetFriendlyFemaleShoesName(itemID), //fo_shoes
		300 => GetFriendlyHairBackName(itemID), //so_hair_b
		301 => GetFriendlyHairFrontName(itemID), //so_hair_f
		302 => GetFriendlyHairSideName(itemID), //so_hair_s
		303 => GetFriendlyHairExtensionName(itemID), //so_hair_o
		305 => GetFriendlyHairColorPresetName(itemID), //preset_hair_color
		306 => GetFriendlyHairMeshPatternName(itemID), //st_hairmeshptn
		313 => GetFriendlyFacepaintName(itemID), //st_paint
		314 => GetFriendlyEyebrowName(itemID), //st_eyebrow
		315 => GetFriendlyEyelashTypeName(itemID), //st_eyelash
		316 => GetFriendlyEyeshadowName(itemID), //st_eyeshadow
		317 => GetFriendlyIrisName(itemID), //st_eye
		318 => GetFriendlyPupilName(itemID), //st_eyeblack
		319 => GetFriendlyEyeHighlightName(itemID), //st_eye_hl
		320 => GetFriendlyBlushName(itemID), //st_cheek
		322 => GetFriendlyLipstickName(itemID), //st_lip
		323 => GetFriendlyMoleName(itemID), //st_mole
		334 => GetFriendlyNippleName(itemID), //st_nip
		335 => GetFriendlyPubicHairName(itemID), //st_underhair
		336 => GetFriendlySkinColorPresetName(itemID), //preset_skin_color
		348 => GetFriendlyClothingPatternByID(itemID), //st_pattern
		350 => "None", //ao_none
		351 => GetFriendlyHeadAccessoryName(itemID), //ao_head
		352 => GetFriendlyEarringName(itemID), //ao_ear
		353 => GetFriendlyGlassesName(itemID), //ao_glasses
		354 => GetFriendlyFaceAccessoryName(itemID), //ao_face
		355 => GetFriendlyNeckAccessoryName(itemID), //ao_neck
		356 => GetFriendlyShoulderAccessoryName(itemID), //ao_shoulder
		357 => GetFriendlyChestAccessoryName(itemID), //ao_chest
		358 => GetFriendlyWaistAccessoryName(itemID), //ao_waist
		359 => GetFriendlyBackAccessoryName(itemID), //ao_back
		360 => GetFriendlyArmAccessoryName(itemID), //ao_arm
		361 => GetFriendlyHandAccessoryName(itemID), //ao_hand
		362 => GetFriendlyLegAccessoryName(itemID), //ao_leg
		363 => GetFriendlyCrotchAccessoryName(itemID), //ao_kokan
		500 => GetFriendlyMaleCustomPoseName(itemID), //custom_pose_m
		501 => GetFriendlyFemaleCustomPoseName(itemID), //custom_pose_f
		502 => GetFriendlyMaleCustomEyebrowName(itemID), //custom_eyebrow_m
		503 => GetFriendlyFemaleCustomEyebrowName(itemID), //custom_eyebrow_f
		504 or 505 => GetFriendlyCustomEyeName(itemID), //custom_eye_m, custom_eye_f
		506 or 507 => GetFriendlyCustomMouthName(itemID), //custom_mouth_m, custom_mouth_f
		_ => $"Unknown category ID {categoryID}, item ID {itemID}"
	};
	public static string GetFriendlyClothingPatternByID(in int itemID) => itemID switch // 348 st_pattern
	{
		0 => "None",
		1 => "Strap",
		2 => "Border",
		3 => "Checkered A",
		4 => "Polka Dot",
		5 => "Strawberry",
		6 => "Harlequin",
		7 => "Star B",
		8 => "Heart",
		9 => "Checkered B",
		10 => "Houndstooth",
		11 => "Net",
		12 => "Leopard",
		13 => "Zebra",
		14 => "Camouflage",
		15 => "Brick",
		16 => "Weave",
		17 => "Square",
		18 => "Flax",
		19 => "Fan Wave",
		20 => "Scroll",
		21 => "Arrowhead",
		22 => "Nordic",
		23 => "Spotted",
		24 => "Turtleshell",
		25 => "Star A",
		26 => "Skull",
		27 => "Gradated Border",
		28 => "Flower",
		29 => "Vertical Stripes",
		30 => "Horizontal Stripes",
		31 => "Mosaic",
		32 => "Argyle",
		33 => "Chimayo",
		34 => "Gingham Checkers",
		35 => "Irregular Stripes",
		36 => "Irregular Border",
		37 => "Circles",
		38 => "Paisley",
		39 => "Ancient",
		40 => "Tropical Leaves",
		41 => "Hibiscus",
		42 => "SPORTS DAY",
		43 => "Thin Stripes",
		44 => "Rose",
		45 => "Dirty",
		46 => "0",
		47 => "0",
		48 => "牡丹",
		49 => "雪輪",
		50 => "毬",
		51 => "菊",
		52 => "桜",
		53 => "霞桜",
		54 => "八つ藤",
		55 => "鳥流水",
		56 => "大花柄",
		57 => "菊唐草",
		58 => "梅唐草",
		59 => "松皮菱",
		60 => "波",
		_ => "Unknown"
	};
}
